Repository Simon-Initiative/oli-torus, pull requests merged in 2022-06, with the labels that each got.

#2602 [BUGFIX][MER-1203] Institution link must only appear for admins in the sections overview page
  lib/oli_web/live/sections/overview_view.ex
  test/oli_web/live/sections/overview_live_test.exs
  test/support/test_helpers.ex
Labels: low-risk

#2606 [MER-1172] Fix ordering in LMS grade updates page
  lib/oli_web/live/grades/updates_table_model.ex
  test/oli_web/live/browse_updates_live_test.exs
  test/support/factory.ex
Labels: low-risk

#2690 [BUGFIX] [MER-1099] Admin sections improvements
  assets/styles/authoring/admin.scss
  lib/oli/delivery/sections/browse.ex
  test/oli/delivery/sections/browse_test.exs
  test/oli_web/live/sections/admin_index_live_test.exs
Labels: low-risk

#2670 [BUGFIX] [MER-1227] [MER-1236] Discount fixes
  lib/oli/delivery/paywall.ex
  lib/oli/delivery/paywall/discount.ex
  lib/oli/utils.ex
  lib/oli_web/live/products/payments/discounts/form.ex
  test/oli/delivery/paywall_test.exs
Labels: low-risk

#2695 [MER-1223] Improve publishing a project waiting time
  config/dev.exs
  config/test.exs
  lib/oli/publishing.ex
  lib/oli/publishing/part_mapping_refresh_adapter.ex
  lib/oli/publishing/part_mapping_refresh_async.ex
  lib/oli/utils/db_seeder.ex
  priv/repo/migrations/20220615201219_remove_part_mapping_refresh_trigger.exs
  test/oli/publishing_test.exs
  test/support/part_mapping_mock_adapter.ex
Labels: medium-risk

#2688 [MER-1230] Update texts to project instead of course project in admin…
  lib/oli_web/live/admin/admin_view.ex
  lib/oli_web/live/community_live/associated/table_model.ex
  lib/oli_web/live/delivery/table_model.ex
  lib/oli_web/live/ingest/ingest.ex
  lib/oli_web/live/ingest/ingest.sface
  lib/oli_web/templates/email/collaborator_invitation.html.eex
  lib/oli_web/templates/project/overview.html.eex
Labels: low-risk

#2725 [MER-1201] Formula editing
  assets/src/components/common/Formula.tsx
  assets/src/components/common/MathJaxFormula.tsx
  assets/src/components/editing/editor/modelEditorDispatch.tsx
  assets/src/components/editing/elements/callout/CalloutElement.tsx
  assets/src/components/editing/elements/callout/calloutActions.ts
  assets/src/components/editing/elements/formula/FormulaEditor.tsx
  assets/src/components/editing/elements/formula/FormulaModal.tsx
  assets/src/components/editing/elements/formula/FormulaToolbar.tsx
  assets/src/components/editing/elements/formula/formulaActions.tsx
  assets/src/components/editing/toolbar/editorToolbar/Inlines.tsx
  assets/src/components/editing/toolbar/editorToolbar/blocks/blockInsertOptions.ts
  assets/src/data/content/model/elements/factories.ts
  assets/src/data/content/model/elements/types.ts
  assets/src/data/content/model/schema.ts
  assets/src/data/content/writers/html.tsx
  assets/src/data/content/writers/writer.tsx
  assets/styles/authoring/formula.scss
  assets/styles/authoring/index.scss
  assets/styles/common/elements.scss
  lib/oli/rendering/content.ex
  lib/oli/rendering/content/html.ex
  lib/oli/rendering/content/plaintext.ex
  lib/oli_web/templates/layout/authoring.html.leex
  priv/schemas/v0-1-0/content-element.schema.json
  test/oli/rendering/content/example_content.json
  test/oli/rendering/content/html_test.exs
  test/oli/rendering/content/plaintext_test.exs
Labels: Enhancement

#2726 [MER-1210] Fix section cost changes not updating for students
  lib/oli_web/controllers/payment_controller.ex
  test/oli_web/controllers/api/payment_controller_test.exs
Labels: medium-risk

#2750 [MER-1297] Attempt fix for part mapping refresh not being executed
  lib/oli/publishing/part_mapping_refresh_async.ex
Labels: low-risk
