Repository Simon-Initiative/oli-torus, pull requests merged in 2025-10, with the labels that each got.

#5926 [FEATURE] [MER-4666] Better search for "Browse all" type tables in Admin workspace
  assets/css/app.css
  lib/oli/authoring/course.ex
  lib/oli/delivery/sections/blueprint.ex
  lib/oli/delivery/sections/browse.ex
  lib/oli_web/live/common/utils.ex
  lib/oli_web/live/products/products_table_model.ex
  lib/oli_web/live/products/products_view.ex
  lib/oli_web/live/projects/projects_live.ex
  lib/oli_web/live/projects/table_model.ex
  lib/oli_web/live/sections/sections_view.ex
  lib/oli_web/live/sections/table_model.ex
  test/oli/course_browse_test.exs
  test/oli_web/live/products_test.exs
  test/oli_web/live/projects_live_test.exs
  test/oli_web/live/sections/admin_index_live_test.exs
Labels: Area: Admin Tools, risk/medium

#5900 [FEATURE] [MER-4701] Related activities for objectives and subobjectives
  lib/oli/delivery/sections.ex
  lib/oli/delivery/sections/post_processing.ex
  lib/oli/delivery/sections/section_resource.ex
  lib/oli/delivery/sections/section_resource_depot.ex
  lib/oli_web/components/delivery/learning_objectives/learning_objectives.ex
  lib/oli_web/components/delivery/learning_objectives/objectives_table_model.ex
  lib/oli_web/components/delivery/learning_objectives/related_activities_table_model.ex
  lib/oli_web/live/common/utils.ex
  lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex
  lib/oli_web/live/delivery/instructor_dashboard/learning_objectives/related_activities_live.ex
  lib/oli_web/router.ex
  priv/repo/migrations/20250924163704_add_related_activities_to_section_resources.exs
  priv/repo/migrations/20250924163747_populate_related_activities_for_existing_section_resources.exs
  test/oli/delivery/sections/post_processing_test.exs
  test/oli/delivery/sections/section_resource_depot_test.exs
  test/oli/delivery/sections_test.exs
  test/oli/sections_test.exs
  test/oli_web/live/delivery/instructor_dashboard/insights/learning_objectives_tab_test.exs
  test/oli_web/live/delivery/instructor_dashboard/learning_objectives/related_activities_live_test.exs
  test/oli_web/live/delivery/student_dashboard/components/learning_objectives_tab_test.exs
Labels: risk/high

#5936 [BUG FIX] [MER-4844] Grammar corrections
  assets/src/apps/page-editor/PageTriggerEditor.tsx
  assets/src/components/editing/elements/trigger/TriggerEditor.tsx
Labels: risk/low

#5937 [ENHANCEMENT] [MER-4826] Include superactivity log messages in DataShop export
  .gitignore
  config/config.exs
  config/dev.exs
  config/test.exs
  lib/mix/tasks/process_custom_activity_logs.ex
  lib/oli/analytics/xapi/events/attempt/tutor_message.ex
  lib/oli/analytics/xapi/local_file_uploader.ex
  lib/oli/delivery/custom_activity_logs.ex
  lib/oli/delivery/custom_logs/legacy_logs.ex
  lib/oli/delivery/custom_logs/utils.ex
  lib/oli/delivery/custom_logs/worker.ex
  lib/oli_web/controllers/legacy_logs_controller.ex
  lib/oli_web/controllers/legacy_superactivity_controller.ex
  oli.example.env
  test/oli/delivery/custom_logs/legacy_logs_test.exs
  test/support/dataset/python/dataset/local_datashop.py
  test/support/dataset/python/generate_local_datashop.py
  test/support/dataset/python/requirements.txt
  test/support/python_runner.ex
  test/test_helper.exs
Labels: risk/high

#5938 [FEATURE] [MER-4706] Scored Pages Filters
  lib/oli_web/components/delivery/content/card_highlights.ex
  lib/oli_web/components/delivery/practice_activities/practice_activities.ex
  lib/oli_web/components/delivery/scored_activities/scored_activities.ex
  lib/oli_web/live/common/table/striped_paged_table.ex
  lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex
  test/oli_web/components/delivery/scored_activities/scored_activities_test.exs
  test/oli_web/live/delivery/instructor_dashboard/overview/practice_activities_tab_test.exs
Labels: risk/medium

#5932 [FEATURE] [MER-4464] Key notion content popup
  assets/src/components/content/Popup.tsx
  assets/src/components/hooks/useAudio.tsx
  assets/src/hooks/use_pointer_capability.ts
  assets/test/components/content/popup_test.tsx
Labels: risk/medium

#5942 [BUG FIX] [MER-5013] Fix spacebar in input
  assets/src/components/video_player/VideoPlayer.tsx
Labels: risk/low

#5941 [FEATURE] [MER-4698] Instructor interface dropdown navigation - part 1
  lib/oli_web/components/delivery/content/content.ex
  lib/oli_web/components/delivery/content/progress.ex
  lib/oli_web/components/delivery/pages/activities_table_model.ex
  lib/oli_web/components/delivery/pages/pages.ex
  lib/oli_web/components/delivery/pages/pages_table_model.ex
  lib/oli_web/components/delivery/practice_activities/practice_activities.ex
  lib/oli_web/components/delivery/practice_activities/practice_assessments_table_model.ex
  lib/oli_web/components/delivery/students/students.ex
  lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex
  lib/oli_web/router.ex
  test/oli_web/components/delivery/scored_activities/activities_table_model_test.exs
  test/oli_web/components/delivery/scored_activities/assessments_table_model_test.exs
  test/oli_web/components/delivery/scored_activities/scored_activities_test.exs
  test/oli_web/live/delivery/instructor_dashboard/insights/students_tab_test.exs
  test/oli_web/live/delivery/instructor_dashboard/overview/practice_activities_tab_test.exs
Labels: risk/high

#5904 [MER-4702] Learning Objectives Expanded Distribution Visualization - Part 1
  assets/src/apps/Components.tsx
  assets/src/components/misc/DotDistributionChart.tsx
  assets/src/components/misc/VegaLiteRenderer.tsx
  assets/test/components/misc/DotDistributionChart_test.tsx
  assets/test/components/misc/VegaLiteRenderer_test.tsx
  lib/oli/delivery/metrics.ex
  lib/oli/delivery/sections.ex
  lib/oli/delivery/sections/section_resource_depot.ex
  lib/oli_web/components/delivery/learning_objectives/expanded_objective_view.ex
  lib/oli_web/components/delivery/learning_objectives/learning_objectives.ex
  lib/oli_web/components/delivery/learning_objectives/objectives_table_model.ex
  lib/oli_web/components/delivery/learning_objectives/sub_objectives_list.ex
  lib/oli_web/components/delivery/learning_objectives/sub_objectives_table_model.ex
  lib/oli_web/live/common/sortable_table/striped_table.ex
  lib/oli_web/live/common/sortable_table/table.ex
  lib/oli_web/live/common/table/striped_paged_table.ex
  lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex
  test/oli/analytics/summary/metrics_v2_test.exs
  test/oli_web/components/delivery/learning_objectives/expanded_objective_view_test.exs
  test/oli_web/components/delivery/learning_objectives/sub_objectives_list_test.exs
Labels: risk/high
