Repository Simon-Initiative/oli-torus, pull requests merged in 2025-09, with the labels that each got.

#5884 [BUG FIX] [MER-4936] Redirect to appropriate page when following invite link and using SSO Sign Up
  lib/oli_web/controllers/delivery_controller.ex
  lib/oli_web/live/user_registration_live.ex
Labels: Hotfix

#5893 [BUG FIX] [MER-4956] Captcha Loop if student is invited via email, but signs-in with invitation link
  lib/oli/delivery/sections.ex
Labels: Hotfix

#5892 [CHORE] [MER-0000] changes
  .github/workflows/ai-review.yml
  .review/elixir.md
  dangerfile.ts
Labels: risk/low, risk/high

#5898 [CHORE] [MER-0000] Filter comments to only those in the delta of the PR
  .github/workflows/ai-review.yml
Labels: risk/low

#5890 [FEATURE] [MER-4710] Practice Pages Formatting Table UI
  lib/oli_web/components/delivery/content/card_highlights.ex
  lib/oli_web/components/delivery/content/content.ex
  lib/oli_web/components/delivery/content/multi_select.ex
  lib/oli_web/components/delivery/content/progress.ex
  lib/oli_web/components/delivery/learning_objectives/learning_objectives.ex
  lib/oli_web/components/delivery/practice_activities/practice_activities.ex
  lib/oli_web/components/delivery/practice_activities/practice_assessments_table_model.ex
  lib/oli_web/components/delivery/students/students.ex
  lib/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live.ex
  test/oli_web/live/delivery/instructor_dashboard/instructor_dashboard_live_test.exs
  test/oli_web/live/delivery/instructor_dashboard/overview/practice_activities_tab_test.exs
Labels: risk/medium

#5903 [FEATURE] [MER-4668] Browse all table tags - rework
  lib/oli_web/live/components/tags/tags_component.ex
Labels: risk/low

#5925 [BUG FIX] [MER-000] devmode.sh quote claude alias body with argument
  devmode.sh
Labels: risk/low

#5927 [FIX] Removes prefetching logiclab in delivery.
  assets/src/components/activities/logic_lab/LogicLabDelivery.tsx
  assets/src/components/activities/logic_lab/LogicLabModelSchema.tsx
Labels: risk/low

#5931 [BUG FIX] [MER-4992] fix right-to-left text in mcq/CATA/ordering choice delivery
  assets/src/components/activities/common/choices/delivery/ChoicesDelivery.modules.scss
  assets/src/components/activities/common/choices/delivery/ChoicesDelivery.tsx
  assets/src/components/activities/ordering/sections/ResponseChoices.tsx
  assets/src/components/common/DraggableColumn.tsx
Labels: Hotfix, frontend
